server:
  port: 8384

spring:
  datasource:
    # 本地db文件的路径
    url: jdbc:sqlite:d:/logCollector.db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

config:
  max-page-size: 100
  max-lines-per-result-with-null-uid: 20
  max-bytes-return: 10000000