server:
  port: 8384

spring:
  datasource:
    # 本地db文件的路径
    url: jdbc:sqlite:d:/logCollector.db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

config:
  # 待扫描的目录，多个使用“;”进行分隔
  dirs-to-scan: E:\logDir
  # 行解析的正则
  line-parse-regex: xxxx
  # 每读取多少行进行一次批量保存
  lines-to-batch-save: 10000
  # 每次数据库查询时，单个分页最大查询数量
  max-page-size: 100
  # 当日志行没有uid时，每条查询结果允许包含的最大行数
  max-lines-per-result-with-null-uid: 20
  # 返回给客户端结果的最大字节数
  max-bytes-return: 10000000