server:
  port: 8384

config:
  # 待扫描的目录，多个使用“;”进行分隔
  dirs-to-scan: E:\logDir
  # 用于存放索引的目录
  dir-for-indexes: E:\logIndexes
  # 当天日志文件的命名
  log-today-file-name: test.log
  # 历史日志文件的命名，使用<?TimeFormat?>作时间占位
  log-history-file-name: test<?yy-MM-dd?>.log
  # 日志的字符集
  log-charset: utf-8
  # 行解析的正则
  line-parse-regex: ^(?<time>.{10} .{8})\.\d{3}\s+(?<level>INFO|WARN|ERROR) (?<uid>.+?) --- \[\s*(?<thread>.+?)] :\s{1}(?<content>.*)
  #  line-parse-regex: ^\[(?<time>.{17})] \[(?<level>INFO|WARN|ERROR)] \[(?<thread>.+?)] \{(?<pos>.+?)}-(?<content>.*)
  # 标签解析的正则
  tag-parse-regex: ^FLAG-(?<key>.+?)-(?<value>.*)
  # 行的时间格式
  line-time-format: "yyyy-MM-dd HH:mm:ss"
  # 需要建立索引的标签，多个使用“;”进行分隔
  tags-to-index: url;user
  # 当新记录与旧记录间不超过指定字节数时，将新记录合并至旧记录
  max-bytes-gap-to-merge: 10000
  # 一次查询，最多返回的结果条数
  default-max-result-count: 30
  # 当日志行没有uid时，每条查询结果允许包含的最大行数
  max-lines-per-result-with-null-uid: 20
  # 定时清理内存context的间隔
  timer-clear-context-sec: 300
  # 定时清理本地索引文件的间隔
  timer-clear-indexes-sec: 172800